services:
    form_generator.property.names_reader:
        class: Lzakrzewski\SymfonyFormGenerator\Property\PropertyNamesReader

    form_generator.extension.form_generator:
        class: Lzakrzewski\SymfonyFormGenerator\Form\Extension\Core\FormGeneratorExtension

    form_generator.property_type_mapper:
        class: Lzakrzewski\SymfonyFormGenerator\Property\PropertyTypeToFormTypeMapper
        calls:
            - [applyDefaultMappings]

    form_generator.guesser.form_annotation:
        class: Lzakrzewski\SymfonyFormGenerator\Guesser\FormAnnotationGuesser
        tags:
            - { name: form_generator.guesser, priority: 100 }

    form_generator.guesser.type_hint:
        class: Lzakrzewski\SymfonyFormGenerator\Guesser\TypeHintGuesser
        arguments:
            - "@form_generator.property_type_mapper"
        tags:
            - { name: form_generator.guesser, priority: 80 }

    form_generator.guesser.validator:
        class: Lzakrzewski\SymfonyFormGenerator\Guesser\ValidatorGuesser
        arguments:
            - "@form_generator.property_type_mapper"
            - "@form.type_guesser.validator"
        tags:
            - { name: form_generator.guesser, priority: 60 }

    form_generator.guesser.php_doc:
        class: Lzakrzewski\SymfonyFormGenerator\Guesser\PHPDocGuesser
        arguments:
            - "@form_generator.property_type_mapper"
        tags:
            - { name: form_generator.guesser, priority: 70 }

    form_generator.guesser.chain:
        class: Lzakrzewski\SymfonyFormGenerator\Guesser\ChainGuesser

    form_generator:
        class: Lzakrzewski\SymfonyFormGenerator\Generator
        arguments:
            - "@form.factory"
            - "@form_generator.property.names_reader"
            - "@form_generator.guesser.chain"